//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Poruke {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Poruke() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Administracija.Poruke", typeof(Poruke).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa je obavezno polje!.
        /// </summary>
        internal static string adresa_req {
            get {
                return ResourceManager.GetString("adresa_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greska u cijenu.
        /// </summary>
        internal static string cijena_e {
            get {
                return ResourceManager.GetString("cijena_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sigurno unosite cijenu.
        /// </summary>
        internal static string cijena_q {
            get {
                return ResourceManager.GetString("cijena_q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena je obavezno polje!.
        /// </summary>
        internal static string cijena_req {
            get {
                return ResourceManager.GetString("cijena_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail adresa je zauzeta!.
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešan format e-mail adrese!.
        /// </summary>
        internal static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail korisnika je obavezno polje!.
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina izgradnje je obavezno polje!.
        /// </summary>
        internal static string godina_req {
            get {
                return ResourceManager.GetString("godina_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grijanje je obavezno polje!.
        /// </summary>
        internal static string grijanje_req {
            get {
                return ResourceManager.GetString("grijanje_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri dodavanju proizvoda!.
        /// </summary>
        internal static string item_err {
            get {
                return ResourceManager.GetString("item_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanton je obavezno polje!.
        /// </summary>
        internal static string kant_req {
            get {
                return ResourceManager.GetString("kant_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija je obavezno polje!.
        /// </summary>
        internal static string kategorije_req {
            get {
                return ResourceManager.GetString("kategorije_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvadrati su obavezno polje!.
        /// </summary>
        internal static string kvadrati_req {
            get {
                return ResourceManager.GetString("kvadrati_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime korisnika je obavezno polje!.
        /// </summary>
        internal static string lname_req {
            get {
                return ResourceManager.GetString("lname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime ili lozinka nisu ispravni!.
        /// </summary>
        internal static string login_err {
            get {
                return ResourceManager.GetString("login_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime korisnika je obavezno polje!.
        /// </summary>
        internal static string name_req {
            get {
                return ResourceManager.GetString("name_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv je obavezno polje!.
        /// </summary>
        internal static string naziv_req {
            get {
                return ResourceManager.GetString("naziv_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite obavezna polja!.
        /// </summary>
        internal static string nekre_bad {
            get {
                return ResourceManager.GetString("nekre_bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nekretnina uspješno sačuvana..
        /// </summary>
        internal static string nekre_succ {
            get {
                return ResourceManager.GetString("nekre_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka treba da sadrži najmanje 4 karaktera!.
        /// </summary>
        internal static string password_err {
            get {
                return ResourceManager.GetString("password_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj karaktera lozinke treba da bude od 8 do 15 i lozinka treba da sadrži bar jedan broj!.
        /// </summary>
        internal static string password_notmatched {
            get {
                return ResourceManager.GetString("password_notmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezno polje!.
        /// </summary>
        internal static string password_req {
            get {
                return ResourceManager.GetString("password_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj prostorija je obavezno polje.
        /// </summary>
        internal static string sobe_req {
            get {
                return ResourceManager.GetString("sobe_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprat je obavezno polje!.
        /// </summary>
        internal static string sprat_req {
            get {
                return ResourceManager.GetString("sprat_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanje je obavezno polje!.
        /// </summary>
        internal static string stanje_req {
            get {
                return ResourceManager.GetString("stanje_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće izmijenuti status prijavljenog korisnika!.
        /// </summary>
        internal static string status_err {
            get {
                return ResourceManager.GetString("status_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon korisnika je obavezno polje!.
        /// </summary>
        internal static string tel_req {
            get {
                return ResourceManager.GetString("tel_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik uspješno dodan..
        /// </summary>
        internal static string user_succ {
            get {
                return ResourceManager.GetString("user_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci uspješno izmijenjeni!.
        /// </summary>
        internal static string user_update_succ {
            get {
                return ResourceManager.GetString("user_update_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto!.
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno polje!.
        /// </summary>
        internal static string username_req {
            get {
                return ResourceManager.GetString("username_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta je obavezno polje!.
        /// </summary>
        internal static string vrste_req {
            get {
                return ResourceManager.GetString("vrste_req", resourceCulture);
            }
        }
    }
}
