//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemNekretnine.DB
{
    using System;
    
    public partial class esp_Pitanja_SelectNeodgovorenaByKorID_Result1
    {
        public int PitanjeID { get; set; }
        public string Pitanje { get; set; }
    }
}
