//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemNekretnine.DB
{
    using System;
    
    public partial class esp_Narudzba_GetByDate_Result1
    {
        public int NarudzbaID { get; set; }
        public string BrojNarudzbe { get; set; }
        public System.DateTime Datum { get; set; }
        public bool Status { get; set; }
        public string ImePrezime { get; set; }
        public int NekretninaID { get; set; }
        public string Naslov { get; set; }
        public Nullable<double> Cijena { get; set; }
    }
}
