//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemNekretnine.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gradovi
    {
        public Gradovi()
        {
            this.Potraznja = new HashSet<Potraznja>();
        }
    
        public int GradID { get; set; }
        public string NazivGarda { get; set; }
        public Nullable<int> KantonID { get; set; }
    
        public virtual Kantoni Kantoni { get; set; }
        public virtual ICollection<Potraznja> Potraznja { get; set; }
    }
}
