//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemNekretnine.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nekretnine
    {
        public Nekretnine()
        {
            this.IzlazStavke = new HashSet<IzlazStavke>();
            this.NarudzbaStavke = new HashSet<NarudzbaStavke>();
            this.Ocjene = new HashSet<Ocjene>();
            this.SlikeNekretnina = new HashSet<SlikeNekretnina>();
            this.Potraznja = new HashSet<Potraznja>();
            this.JavnaPitanja = new HashSet<JavnaPitanja>();
        }
    
        public int NekretninaID { get; set; }
        public Nullable<int> VrstaID { get; set; }
        public Nullable<int> KategorijaID { get; set; }
        public Nullable<int> KantonID { get; set; }
        public Nullable<int> SobeID { get; set; }
        public Nullable<int> SpratID { get; set; }
        public Nullable<int> GrijanjeID { get; set; }
        public Nullable<int> StanjeID { get; set; }
        public Nullable<int> KorisnikID { get; set; }
        public string Naslov { get; set; }
        public Nullable<int> BrojKvadrata { get; set; }
        public string Adresa { get; set; }
        public Nullable<double> Cijena { get; set; }
        public Nullable<int> GodinaIzgradnje { get; set; }
        public Nullable<bool> Voda { get; set; }
        public Nullable<bool> Struja { get; set; }
        public Nullable<bool> Knalizacija { get; set; }
        public Nullable<bool> Uknjiženo { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<bool> Lift { get; set; }
        public Nullable<bool> Namješten { get; set; }
        public Nullable<bool> Internet { get; set; }
        public Nullable<bool> Novogradnja { get; set; }
        public Nullable<bool> NedavnoAdaptiran { get; set; }
        public Nullable<bool> Garaža { get; set; }
        public Nullable<bool> Telefon { get; set; }
        public byte[] SlikaThumb { get; set; }
        public Nullable<System.DateTime> DatumObjave { get; set; }
        public Nullable<int> BrojPosjeta { get; set; }
        public bool Aktivna { get; set; }
    
        public virtual ICollection<IzlazStavke> IzlazStavke { get; set; }
        public virtual Kantoni Kantoni { get; set; }
        public virtual Kategorije Kategorije { get; set; }
        public virtual Kupci Kupci { get; set; }
        public virtual ICollection<NarudzbaStavke> NarudzbaStavke { get; set; }
        public virtual Sobe Sobe { get; set; }
        public virtual Spratovi Spratovi { get; set; }
        public virtual StanjaNekretnina StanjaNekretnina { get; set; }
        public virtual TipGrijanja TipGrijanja { get; set; }
        public virtual VrsteProdaje VrsteProdaje { get; set; }
        public virtual ICollection<Ocjene> Ocjene { get; set; }
        public virtual ICollection<SlikeNekretnina> SlikeNekretnina { get; set; }
        public virtual ICollection<Potraznja> Potraznja { get; set; }
        public virtual ICollection<JavnaPitanja> JavnaPitanja { get; set; }
    }
}
