//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemNekretnine.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potraznja
    {
        public int PotraznjaID { get; set; }
        public int GradID { get; set; }
        public Nullable<int> NekretninaID { get; set; }
        public int KupacID { get; set; }
    
        public virtual Gradovi Gradovi { get; set; }
        public virtual Nekretnine Nekretnine { get; set; }
        public virtual Kupci Kupci { get; set; }
    }
}
